name: Test workflow

on: push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: sudo apt-get install -y valgrind cppcheck
      - name: Cppcheck
        run: cppcheck *.cpp --enable=warning --error-exitcode=1
      - name: Cppcheck report
        run: cppcheck *.cpp --enable=warning,style,performance --output-file=checkreport.txt
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
            name: checkreport
            path: ./checkreport.txt
      - name: New gcc version
        run: sudo apt --only-upgrade install g++-10 gcc-10
      - name: Build
        run: g++-10 -std=c++17 -Wall -Werror *.cpp
      - name: Memory check
        run: valgrind --leak-check=full --error-exitcode=1 ./a.out units/unit1.json units/unit2.json
      - name: Run Test
        run: ./test.sh
      - name: Diff
        run: diff ./units/output1.txt Genoutput1.txt && diff ./units/output2.txt Genoutput2.txt
