name: Test workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: g++ -std=c++17 *.cpp
	  - name: Run test
	    run: ./test.sh
	  - name: diff
	    run: diff output.txt good_output.txt